name: Deploy Contact-List App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy on VM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into VM & run project
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.234.118.198
          username: ubuntu
          key: ${{ secrets.ANIL_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Projects/ContactList-Web
            if ! git pull origin master; then
              echo "Failed to pull latest changes from the repository."
              exit 1
            fi
            docker compose down
            docker compose up -d
            
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
